default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: giordanoalves
  password: password

development:
  <<: *default
  database: gio_pay_development

test:
  <<: *default
  database: gio_pay_test
